/**
 * Decompiled IjkMediaPlayer internal classes from ijkplayer.
 *
 * The helper classes in this package are JADX-decompiled bytecode from the
 * ijkplayer library (https://github.com/bilibili/ijkplayer). They were
 * originally anonymous inner classes and synthetic accessors generated by
 * ProGuard processing of the original IjkMediaPlayer implementation, and have
 * been renamed from their single-letter obfuscated forms to meaningful names:
 *
 * - AndroidMediaPlayerListenerAdapter: 8-in-1 listener adapter for AndroidMediaPlayer
 * - AndroidMediaDataSourceProxy: MediaDataSource proxy wrapping IMediaDataSource
 * - IjkMediaPlayerEventHandler: Handler dispatching native events for IjkMediaPlayer
 * - PreparedListenerProxy / CompletionListenerProxy / BufferingUpdateListenerProxy
 *   / SeekCompleteListenerProxy / VideoSizeChangedListenerProxy / ErrorListenerProxy
 *   / InfoListenerProxy / TimedTextListenerProxy: listener forwarders for MediaPlayerProxy
 *
 * The public API classes (IjkMediaPlayer, IjkMediaFormat, MediaInfo, etc.)
 * retain their original names.
 */
package tv.danmaku.ijk.media.player;
