/**
 * Decompiled IjkMediaPlayer internal classes from ijkplayer.
 *
 * The single-letter classes (a.java through l.java) in this package are
 * JADX-decompiled bytecode from the ijkplayer library
 * (https://github.com/bilibili/ijkplayer). They are anonymous inner classes
 * and synthetic accessors generated by ProGuard processing of the original
 * IjkMediaPlayer implementation. The public API classes
 * (IjkMediaPlayer, IjkMediaFormat, MediaInfo, etc.) retain their original
 * names.
 *
 * TODO: Replace with official ijkplayer dependency or rename to meaningful
 * class names in a future refactor.
 */
package tv.danmaku.ijk.media.player;
